- name: Monitor Windows Server Metrics
  hosts: all
  tasks:
    - name: Check CPU usage
      win_shell: Get-WmiObject Win32_Processor | Select-Object -ExpandProperty LoadPercentage
      register: cpu_usage

    - name: Show CPU usage
      debug:
        msg: "CPU Usage: {{ cpu_usage.stdout }}%"

    - name: Check disk space
      win_shell: Get-PSDrive C | Select-Object -ExpandProperty Free
      register: disk_free

    - name: Show disk space
      debug:
        msg: "Free disk space: {{ disk_free.stdout }} bytes"
