- name: Run Windows Updates with Retry Until No Reboot Required
  hosts: all
  tasks:
    - name: Install security updates
      win_updates:
        category_names:
          - SecurityUpdates
        reboot: yes
      register: updates
      retries: 3
      delay: 60
      until: updates.reboot_required == false

    - name: Check installed updates
      win_shell: Get-HotFix | Sort-Object -Property InstalledOn
      register: hotfixes

    - name: Show installed updates
      debug:
        msg: "{{ hotfixes.stdout_lines }}"