#Terraform and Ansible Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tf_ok: ${{ steps.tf_check.outcome }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python and install Ansible
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible pywinrm requests
          sudo apt-get update && sudo apt-get install -y unzip curl sshpass

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Terraform Init & Plan
        id: tf_check
        working-directory: terraform/vmware
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan

      - name: Save tfplan artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: terraform/vmware/tfplan

  deploy-dev:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Download tfplan artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: terraform/vmware

      - name: Terraform Apply for DEV
        working-directory: terraform/vmware
        run: terraform apply -auto-approve tfplan

  deploy-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Download tfplan artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: terraform/vmware

      - name: Terraform Apply for TEST
        working-directory: terraform/vmware
        run: terraform apply -auto-approve tfplan

#  deploy-prod:
#    needs: setup
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Run Ansible for PROD 
#        run: |
#          pip install ansible pywinrm requests
#          ansible-playbook -i ansible/inventory/prod.yml ansible/playbooks/manage_services.yml
#          ansible-playbook -i ansible/inventory/prod.yml ansible/playbooks/windows_updates.yml
#          ansible-playbook -i ansible/inventory/prod.yml ansible/playbooks/monitoring.yml
#          ansible-playbook -i ansible/inventory/prod.yml ansible/playbooks/antivirus.yml